name: Run Cypress Tests

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
  pull_request_review:
    types: [submitted, edited]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run serve &
        env:
          NODE_ENV: production

      - name: Wait for server to be ready
        run: |
          echo "Waiting for server to start..."
          npx wait-on http://localhost:4000

      - name: Run Cypress
        run: npx cypress run
